use_frameworks!

platform :ios, '11.0'

target 'ZenTextExample' do
  pod 'ZenText', :path => '../'
  pod 'SnapKit'
  target 'ZenTextTests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
